server:
  port: 8088

fiap:
  debug: true

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:/Users/fabiomiyasato/5scjo-alunos-db;DB_CLOSE_ON_EXIT=FALSE
    password: fiap
    username: fiap
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
